### PR TITLE
Update Canadian territories (3) and provinces (10)

### PR DESCRIPTION
**Pull request by tylert**
@DaleFarnsworth

### CODE REVIEW

**Comment by DaleFarnsworth** [comment]
Hmm, this one is slightly problematic.  I hesitate to change the abbreviation code before the corresponding unabbreviate code in https://github.com/KD4Z/md380tools-vm is updated.
I'll put in a pull request to md380tools-vm to change the abbreviation "NL" to be "NewFoundland and Labrador" and for "NU" to be "Nunavut".  After that change has been in for some time, I'll make the corresponding change to userdb.

The addition of Northwest Territories is more problematic.  The md380tools does not handle state/province abbreviations by country.  "NT" is already taking by Australia's Northwest Territory.
I think the best thing is not to abbreviate Northwest Territories, given that there are currently 24 DMR IDs assigned to hams in Northwest Territory and none in Northwest Territories.

**Comment by tylert** [comment]
Wow, that's disappointing they didn't use the ISO 3166 codes for all the provinces and territories :)

I'll trust your judgement.  Please close the PR if you'd prefer to hold off on it for now.

**Comment by tylert** [comment]
Technically, there are ISO 3166-2 codes like "CA-ON" (https://en.wikipedia.org/wiki/ISO_3166-2:CA).

**Comment by DaleFarnsworth** [comment]
Yes, I just looked that up.  They *could* be used, but the changes to the
md380tools firmware would be very substantial.
I'm happy to see the unexpanded abbreviations on my md-uv380.  It wouldn't
look quite so nice seeing "CA-ON".

Oh well.  But, the more I think about it I'm going to go ahead and apply
your commit.  It will be fine.

**Comment by DaleFarnsworth** [comment]
I see that userdb doesn't currently permit duplicate state/province even in different countries.  I'll fix that before applying your commit.

**Comment by DaleFarnsworth** [comment]
I cherry-picked your commit.  Thank you!

**Comment by DaleFarnsworth** [comment]
FYI.  KD4Z merged my PR into his md380tools-vm repo.

**Comment by tylert** [comment]
:+1:

**Pull request closed without merging**
